export default [
    {
        companyName: "PennyFlo",
        position: "Backend Intern",
        startDate: "November 2024",
        endDate: "January 2025",
        companyURL: "https://www.pennyflo.io",
        desc: "I have been working to create a special feature to help users (CFOs) access all their invoices, current balance and projected balance for all the connected bank accounts as well as any external bank statements they upload, in a single dashboard. \nIt also has a chart to get predicted balances for the next 1, 2 or 3 months. \nI have already created the responsive, pixel-perfect components and basic backend logic & integration and have been working on the backend of the feature to optimise it further.",
        techStack: ["Next.js", "TypeScript", "TailwindCSS", "Prisma", "PostgreSQL", "xlsx parser", "Vercel Blob Storage", "Vercel KV Store"],
    },
    {
        companyName: "BespokeDevs",
        position: "Software Engineer Intern",
        startDate: "July 2024",
        endDate: "October 2024",
        companyURL: "https://bespokedevs.com",
        desc: "During my time at BespokeDevs, I co-developed Extractopus, a powerful and efficient lead generation and cold outreach tool designed to streamline business growth. \nThe platform automates the process of extracting high-quality leads and simplifies cold outreach, providing users with a seamless and effective solution by just using the profession keyword user wants to target. \nFrom conceptualization to deployment, I played a significant role by building the complete landing page and several other pages and optimizing the backend calls to reduce cost by 34% by reducing number of calls to Serper, to ensure scalability, responsiveness, and performance.",
        techStack: ["Next.js", "Django", "TypeScript", "TailwindCSS", "Prisma", "Serper API", "PostgreSQL"],
    },
    {
        companyName: "GyaanCentral",
        position: "Software Engineer Intern",
        startDate: "April 2024",
        endDate: "June 2024",
        companyURL: "https://www.linkedin.com/company/gyaan-central",
        desc: "During my time at GyaanCentral, I developed two unique web applications, Vidpedia and YT Robin, from scratch. \nVidpedia is a comprehensive directory of video editing styles and techniques, attracting over 100 global visitors. \nIt features a live database management table for admins, searchable records using Prisma, and Firebase integration for storing GIFs. \nYT Robin is an engaging YouTube Thumbnail Guessing Game styled with a retro Windows UI, with over 200 users worldwide. Both projects showcase my ability to design scalable, user-friendly, and responsive solutions while tackling real-time data updates and state management challenges.",
        techStack: ["Next.js", "TypeScript", "TailwindCSS", "Prisma", "Firebase", "PostgreSQL"],
    },
    {
        companyName: "DevKit",
        position: "Software Engineer Intern",
        startDate: "March 2024",
        endDate: "April 2024",
        companyURL: "https://www.linkedin.com/company/getdevkit",
        desc: "During my time at DevKit, I independently developed a Tweet Data Scraper from scratch to collect and process tweets about tech job and freelance opportunities. \nThe scraper utilized Puppeteer, a headless browser library, to extract tweet content and integrated the OpenAI API to analyze and structure the data before storing it in a PostgreSQL database. \nThe project showcased my ability to deliver efficient, scalable, and visually appealing solutions under tight deadlines.",
        techStack: ["Next.js", "TypeScript", "TailwindCSS", "Puppeteer", "OpenAI API", "PostgreSQL"],
    },
    {
        companyName: "Open Source Contributions",
        position: "Contributor",
        startDate: "",
        endDate: "",
        companyURL: "https://github.com/PrgrmrHarshShukla",
        desc: "I have contributed to renowned open-source projects, such as MetaMask, with over 40 pull requests successfully merged. \nThese contributions involve replacing deprecated components with modern alternatives, updating or modifying component APIs, and ensuring that changes maintain the visual integrity of the UI. \nI rigorously validate my updates through end-to-end tests, Jest tests, linting, and Storybook checks, honing my skills in maintaining high-quality, production-ready code.",
        techStack: ["React", "TypeScript", "Jest", "Storybook", "Git"],
    },
]
